In [5]:
import pandas as pd

In [6]:
from scipy.stats import chi2_contingency
import seaborn as sns
import numpy as np

In [7]:
import numpy as np
import seaborn as sns
from datascience import *
%matplotlib inline

In [8]:
table = pd.read_excel('hxb2f.meth_cleaned_genes.xlsx')

table


Reference_sequence_name  Start_position  End_position_excl  \
0                     HXB2F               2                  3   
1                     HXB2F               6                  7   
2                     HXB2F              23                 24   
3                     HXB2F              24                 25   
4                     HXB2F              37                 38   
..                      ...             ...                ...   
450                   HXB2F            9476               9477   
451                   HXB2F            9491               9492   
452                   HXB2F            9492               9493   
453                   HXB2F            9648               9649   
454                   HXB2F            9649               9650   

    Modification_type  Score Strand  Read_coverage_at_reference  \
0                5hmC     35      -                          28   
1                5hmC     32      -                          31   
2                5hmC    814      +                         108   
3                5hmC    857      -                          35   
4                5hmC      9      +                         108   
..                ...    ...    ...                         ...   
450              5hmC    500      -                           4   
451              5hmC    857      +                           7   
452              5hmC   1000      -                           3   
453              5hmC    857      +                           7   
454              5hmC    500      -                           2   

     Percentage_of_mod_bases Reading_frame_1 Reading_frame_2 Reading_frame_3  \
0                     100.00           LTR_5             NaN             NaN   
1                       0.00           LTR_5             NaN             NaN   
2                       3.41           LTR_5             NaN             NaN   
3                      23.33           LTR_5             NaN             NaN   
4                       0.00           LTR_5             NaN             NaN   
..                       ...             ...             ...             ...   
450                     0.00             NaN           LTR_3             NaN   
451                    16.67             NaN           LTR_3             NaN   
452                     0.00             NaN           LTR_3             NaN   
453                    33.33             NaN           LTR_3             NaN   
454                     0.00             NaN             NaN             NaN   

    in_paper tat_reading rev_reading Unnamed: 14  
0        NaN         NaN         NaN         NaN  
1        NaN         NaN         NaN         NaN  
2        NaN         NaN         NaN         NaN  
3        NaN         NaN         NaN         NaN  
4        NaN         NaN         NaN         NaN  
..       ...         ...         ...         ...  
450      NaN         NaN         NaN         NaN  
451      NaN         NaN         NaN         NaN  
452      NaN         NaN         NaN         NaN  
453      NaN         NaN         NaN         NaN  
454      NaN         NaN         NaN         NaN  

[455 rows x 15 columns]

In [9]:
is_mod = table['Percentage_of_mod_bases']>50
is_mod

0       True
1      False
2      False
3      False
4      False
       ...  
450    False
451    False
452    False
453    False
454    False
Name: Percentage_of_mod_bases, Length: 455, dtype: bool

In [10]:
is_LTR_5 = table['Reading_frame_1'] == 'LTR_5'
is_LTR_5 

0       True
1       True
2       True
3       True
4       True
       ...  
450    False
451    False
452    False
453    False
454    False
Name: Reading_frame_1, Length: 455, dtype: bool

In [11]:
pd.crosstab (is_LTR_5, is_mod)

Percentage_of_mod_bases  False  True
Reading_frame_1                     
False                      336    32
True                        80     7

In [12]:
from scipy.stats import chi2_contingency

In [13]:
delta, p_value, dof, c_expected = chi2_contingency (pd.crosstab (is_LTR_5, is_mod))

In [14]:

print(f'There were {dof} degrees of freedom in the table.')
print(f'It expects to see the matrix\n{c_expected}')

print(f'There was a difference of {delta} between the expected and observed matrices.')
print(f'The likelihood of seeing this large a difference by chance is p={p_value}.')

There were 1 degrees of freedom in the table.
It expects to see the matrix
[[ 336.45714286   31.54285714]
 [  79.54285714    7.45714286]]
There was a difference of 0.0 between the expected and observed matrices.
The likelihood of seeing this large a difference by chance is p=1.0.


In [15]:
# Apperently this is by chance ?????

In [16]:
is_gag = table['Reading_frame_1'] == 'gag'
is_gag 

0      False
1      False
2      False
3      False
4      False
       ...  
450    False
451    False
452    False
453    False
454    False
Name: Reading_frame_1, Length: 455, dtype: bool

In [17]:
pd.crosstab (is_gag, is_mod)

Percentage_of_mod_bases  False  True
Reading_frame_1                     
False                      347    32
True                        69     7

In [18]:
delta_gag, p_value_gag, dof_gag, c_expected_gag = chi2_contingency (pd.crosstab (is_gag, is_mod))

In [19]:
print(f'There were {dof_gag} degrees of freedom in the table.')
print(f'It expects to see the matrix\n{c_expected_gag}')

print(f'There was a difference of {delta_gag} between the expected and observed matrices.')
print(f'The likelihood of seeing this large a difference by chance is p={p_value_gag}.')

There were 1 degrees of freedom in the table.
It expects to see the matrix
[[ 346.51428571   32.48571429]
 [  69.48571429    6.51428571]]
There was a difference of 0.0 between the expected and observed matrices.
The likelihood of seeing this large a difference by chance is p=1.0.


In [20]:
# We see the same in the gag gene as well.

In [21]:
is_pol = table['Reading_frame_3' ] == 'pol'

is_pol

0      False
1      False
2      False
3      False
4      False
       ...  
450    False
451    False
452    False
453    False
454    False
Name: Reading_frame_3, Length: 455, dtype: bool

In [22]:
pd.crosstab (is_pol, is_mod)

Percentage_of_mod_bases  False  True
Reading_frame_3                     
False                      366    29
True                        50    10

In [23]:
delta_pol, p_value_pol, dof_pol, c_expected_pol = chi2_contingency (pd.crosstab (is_gag, is_mod))

In [24]:
print(f'There were {dof_pol} degrees of freedom in the table.')
print(f'It expects to see the matrix\n{c_expected_pol}')

print(f'There was a difference of {delta_pol} between the expected and observed matrices.')
print(f'The likelihood of seeing this large a difference by chance is p={p_value_pol}.')

There were 1 degrees of freedom in the table.
It expects to see the matrix
[[ 346.51428571   32.48571429]
 [  69.48571429    6.51428571]]
There was a difference of 0.0 between the expected and observed matrices.
The likelihood of seeing this large a difference by chance is p=1.0.


# The same for the pol gene. Does Python know that the entire genome of the HIV is 9718? Does that even matter?

In [25]:
is_vif = table['Reading_frame_1' ] == 'vif'
is_vif

0      False
1      False
2      False
3      False
4      False
       ...  
450    False
451    False
452    False
453    False
454    False
Name: Reading_frame_1, Length: 455, dtype: bool

In [26]:
pd.crosstab (is_vif, is_mod)

Percentage_of_mod_bases  False  True
Reading_frame_1                     
False                      409    37
True                         7     2

In [27]:
delta_vif, p_value_vif, dof_vif, c_expected_vif = chi2_contingency (pd.crosstab (is_vif, is_mod))

In [28]:
print(f'There were {dof_vif} degrees of freedom in the table.')
print(f'It expects to see the matrix\n{c_expected_vif}')

print(f'There was a difference of {delta_vif} between the expected and observed matrices.')
print(f'The likelihood of seeing this large a difference by chance is p={p_value_vif}.')

There were 1 degrees of freedom in the table.
It expects to see the matrix
[[ 407.77142857   38.22857143]
 [   8.22857143    0.77142857]]
There was a difference of 0.767791246263079 between the expected and observed matrices.
The likelihood of seeing this large a difference by chance is p=0.3809012164487693.


In [29]:
# That the methylation ion this gene is probably not by random chance. 

In [30]:
is_vpr = table['Reading_frame_3' ] == 'vpr'
is_vpr

0      False
1      False
2      False
3      False
4      False
       ...  
450    False
451    False
452    False
453    False
454    False
Name: Reading_frame_3, Length: 455, dtype: bool

In [31]:
delta_vpr, p_value_vpr, dof_vpr, c_expected_vpr = chi2_contingency (pd.crosstab (is_vpr, is_mod))

In [32]:
print(f'There were {dof_vpr} degrees of freedom in the table.')
print(f'It expects to see the matrix\n{c_expected_vpr}')

print(f'There was a difference of {delta_vpr} between the expected and observed matrices.')
print(f'The likelihood of seeing this large a difference by chance is p={p_value_vpr}.')

There were 1 degrees of freedom in the table.
It expects to see the matrix
[[ 406.85714286   38.14285714]
 [   9.14285714    0.85714286]]
There was a difference of 0.1664179541198501 between the expected and observed matrices.
The likelihood of seeing this large a difference by chance is p=0.6833151061980818.


In [33]:
is_tat = table['tat_reading'] == 'tat'
is_tat


0      False
1      False
2      False
3      False
4      False
       ...  
450    False
451    False
452    False
453    False
454    False
Name: tat_reading, Length: 455, dtype: bool

In [34]:
pd.crosstab (is_tat, is_mod)

Percentage_of_mod_bases  False  True
tat_reading                         
False                      392    38
True                        24     1

In [35]:
delta_tat, p_value_tat, dof_tat, c_expected_tat = chi2_contingency (pd.crosstab (is_tat, is_mod))

In [36]:
print(f'There were {dof_tat} degrees of freedom in the table.')
print(f'It expects to see the matrix\n{c_expected_tat}')

print(f'There was a difference of {delta_tat} between the expected and observed matrices.')
print(f'The likelihood of seeing this large a difference by chance is p={p_value_tat}.')

There were 1 degrees of freedom in the table.
It expects to see the matrix
[[ 393.14285714   36.85714286]
 [  22.85714286    2.14285714]]
There was a difference of 0.22320130813953498 between the expected and observed matrices.
The likelihood of seeing this large a difference by chance is p=0.6366114337797564.


In [37]:
# WRITE HERE!

In [38]:
is_rev = table['rev_reading' ] == 'rev'
is_rev

0      False
1      False
2      False
3      False
4      False
       ...  
450    False
451    False
452    False
453    False
454    False
Name: rev_reading, Length: 455, dtype: bool

In [39]:
pd.crosstab (is_rev, is_mod)

Percentage_of_mod_bases  False  True
rev_reading                         
False                      410    38
True                         6     1

In [40]:
delta_rev, p_value_rev, dof_rev, c_expected_rev = chi2_contingency (pd.crosstab (is_rev, is_mod))

In [41]:
print(f'There were {dof_rev} degrees of freedom in the table.')
print(f'It expects to see the matrix\n{c_expected_rev}')

print(f'There was a difference of {delta_rev} between the expected and observed matrices.')
print(f'The likelihood of seeing this large a difference by chance is p={p_value_rev}.')

There were 1 degrees of freedom in the table.
It expects to see the matrix
[[ 409.6   38.4]
 [   6.4    0.6]]
There was a difference of 0.0 between the expected and observed matrices.
The likelihood of seeing this large a difference by chance is p=1.0.


In [42]:
# WRITE HERE

In [43]:
is_env = table['Reading_frame_3'] == 'env'
is_env

0      False
1      False
2      False
3      False
4      False
       ...  
450    False
451    False
452    False
453    False
454    False
Name: Reading_frame_3, Length: 455, dtype: bool

In [44]:
pd.crosstab (is_env, is_mod)

Percentage_of_mod_bases  False  True
Reading_frame_3                     
False                      320    34
True                        96     5

In [45]:
delta_env, p_value_env, dof_env, c_expected_env = chi2_contingency (pd.crosstab (is_env, is_mod))

In [46]:
print(f'There were {dof_env} degrees of freedom in the table.')
print(f'It expects to see the matrix\n{c_expected_env}')

print(f'There was a difference of {delta_env} between the expected and observed matrices.')
print(f'The likelihood of seeing this large a difference by chance is p={p_value_env}.')

There were 1 degrees of freedom in the table.
It expects to see the matrix
[[ 323.65714286   30.34285714]
 [  92.34285714    8.65714286]]
There was a difference of 1.6186020416130593 between the expected and observed matrices.
The likelihood of seeing this large a difference by chance is p=0.2032868231345772.


In [47]:
#Write Here!

In [48]:
is_LTR_3 = table['Reading_frame_2'] == 'LTR_3'
is_LTR_3

0      False
1      False
2      False
3      False
4      False
       ...  
450     True
451     True
452     True
453     True
454    False
Name: Reading_frame_2, Length: 455, dtype: bool

In [49]:
pd.crosstab (is_LTR_3, is_mod)

Percentage_of_mod_bases  False  True
Reading_frame_2                     
False                      391    37
True                        25     2

In [50]:
delta_LTR_3, p_value_LTR_3, dof_LTR_3, c_expected_LTR_3 = chi2_contingency (pd.crosstab (is_LTR_3, is_mod))

In [51]:
print(f'There were {dof_LTR_3} degrees of freedom in the table.')
print(f'It expects to see the matrix\n{c_expected_LTR_3}')

print(f'There was a difference of {delta_LTR_3} between the expected and observed matrices.')
print(f'The likelihood of seeing this large a difference by chance is p={p_value_LTR_3}.')

There were 1 degrees of freedom in the table.
It expects to see the matrix
[[ 391.31428571   36.68571429]
 [  24.68571429    2.31428571]]
There was a difference of 0.0 between the expected and observed matrices.
The likelihood of seeing this large a difference by chance is p=1.0.


In [51]:
WRITE HERE!

In [53]:
table

Reference_sequence_name  Start_position  End_position_excl  \
0                     HXB2F               2                  3   
1                     HXB2F               6                  7   
2                     HXB2F              23                 24   
3                     HXB2F              24                 25   
4                     HXB2F              37                 38   
..                      ...             ...                ...   
450                   HXB2F            9476               9477   
451                   HXB2F            9491               9492   
452                   HXB2F            9492               9493   
453                   HXB2F            9648               9649   
454                   HXB2F            9649               9650   

    Modification_type  Score Strand  Read_coverage_at_reference  \
0                5hmC     35      -                          28   
1                5hmC     32      -                          31   
2                5hmC    814      +                         108   
3                5hmC    857      -                          35   
4                5hmC      9      +                         108   
..                ...    ...    ...                         ...   
450              5hmC    500      -                           4   
451              5hmC    857      +                           7   
452              5hmC   1000      -                           3   
453              5hmC    857      +                           7   
454              5hmC    500      -                           2   

     Percentage_of_mod_bases Reading_frame_1 Reading_frame_2 Reading_frame_3  \
0                     100.00           LTR_5             NaN             NaN   
1                       0.00           LTR_5             NaN             NaN   
2                       3.41           LTR_5             NaN             NaN   
3                      23.33           LTR_5             NaN             NaN   
4                       0.00           LTR_5             NaN             NaN   
..                       ...             ...             ...             ...   
450                     0.00             NaN           LTR_3             NaN   
451                    16.67             NaN           LTR_3             NaN   
452                     0.00             NaN           LTR_3             NaN   
453                    33.33             NaN           LTR_3             NaN   
454                     0.00             NaN             NaN             NaN   

    in_paper tat_reading rev_reading Unnamed: 14  
0        NaN         NaN         NaN         NaN  
1        NaN         NaN         NaN         NaN  
2        NaN         NaN         NaN         NaN  
3        NaN         NaN         NaN         NaN  
4        NaN         NaN         NaN         NaN  
..       ...         ...         ...         ...  
450      NaN         NaN         NaN         NaN  
451      NaN         NaN         NaN         NaN  
452      NaN         NaN         NaN         NaN  
453      NaN         NaN         NaN         NaN  
454      NaN         NaN         NaN         NaN  

[455 rows x 15 columns]

In [52]:
# I did this by hand, took a while.

# positions 2, 95, 186, 332, 410, 420, 463, 597 were found to be methylated in 50% of each Read_coverage_at_reference from the table. 
total_bases_LTR_five = 634
total_mod_LTR_five = 88
total_unmod_LTR_five = 546
mod_LTR_five_above_cut_off = 7


# positions 1374, 1582, 1854, 1858, 1879, 2138, 2164 were found to be methylated in >50% of each Read_coverage_at_reference from the table.
total_bases_gag = 1523
total_mod_gag = 75
total_unmod_gag = 1448
mod_gag_above_cut_off = 7


# positions 3212, 3466, 3829, 4038, 4052, 4092, 4153, 4184, 4598, 4664 were found to be methylated >50% of each Read_coverage_at_reference from the table.
total_bases_pol = 2738
total_mod_pol = 59
total_unmod_pol = 2679
mod_pol_above_cut_off = 10

# positions 5448, 5449 were found to be methylated >50% of each Read_coverage_at_reference from the table.
total_bases_vif = 578
total_mod_vif = 8
total_unmod_vif = 570
mod_vif_above_cut_off = 2

# No positions were found to be methylated in >50% of each Read_coverage_at_reference from the table.
total_base_vpr = 280
total_mod_vpr = 10
total_unmod_vpr  = 270
mod_vpr_above_cut_off = 0

# positions 5984 was found to be methylated >50% of each Read_coverage_at_reference from the table.
total_bases_tat = 301
total_mod_tat = 25
total_unmod_tat = 276
mod_tat_above_cut_off = 1

# positions 5984 was found to be methylated >50% of each Read_coverage_at_reference from the table.
total_bases_rev = 349
total_mod_rev = 39
total_unmod_rev = 310
mod_rev_above_cut_off = 1

# positions 7357, 7633, 7785, 8179, 8323,  were found to be methylated >50% of each Read_coverage_at_reference from the table.
total_bases_env = 2570
total_mod_env = 100
total_unmod_env = 2470
mod_env_above_cut_off = 5

# positions 8846, 8980, 9002, 9161, 9165 were found to be methylated >50% of each Read_coverage_at_reference from the table.
total_bases_nef = 617
total_mod_nef = 43
total_unmod_nef = 617
mod_nef_above_cut_off = 5

# positions 9161, 9165 were found to be methylated >50% of each Read_coverage_at_reference from the table.
total_bases_LTR_three = 633
total_mod_LTR_three = 27
total_unmod_LTR_three = 606
mod_LTR_three_above_cut_off = 2

# positions 700, 680 were found to be methylated >50% of each Read_coverage_at_reference from the table.
total_mod_bases_no_gene = 46
total_unmod_no_gene = 123
mod_no_gene_above_cut_off = 2

